#baseURL = "https://jp-guimaraes.github.io/nomedorepo/"
baseURL = "localhost"
languageCode = "en-us"
title = "Fontes"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

